### ISSUE TITLE
[Task 1.4] Improving Coverage

### ISSUE THREAD

**Issue by woohyun7878** [cs169/fa23-chips-10.5-18#11]
Update SimpleCov Config:
Edit features/support/env.rb and spec/rails_helper.rb.
Set SimpleCov to exclude /lib folder.
Execute bundle exec rspec and bundle exec cucumber.
Check coverage in coverage/index.html.
Identify files in /app with low coverage.
Write additional tests to cover gaps.

Expected Outcome
Test coverage for /app exceeds 45%.

**Comment by Madelen143** [comment]
lgtm
