### ISSUE TITLE
[Task 1.3] Fix and Enhance Functionality of Counties Map

### ISSUE THREAD

**Issue by woohyun7878** [cs169/fa23-chips-10.5-18#12]
### Identify Issue:
- Analyze the current map functionality to understand the breakdown in interactivity.

### Code Integration:
- Utilize JavaScript to link county clicks to the `search#search` route.
- Ensure the correct URL is triggered upon clicking a county.

### Testing:
- Write Cucumber tests to validate the map's functionality.

### Expected Outcome:
- Users can click on a county and see the corresponding representatives.
- Enhanced user interaction and functionality of the map feature.

**Comment by rachaelhan28** [comment]
completed iteration 1
